# Customer Churn Prediction

Customer churn is the rate at which customers stop doing business, cancel subscriptions, or cease using a company's services over a specific period. We are gonna predict customer's churn for the Telco Company.

The dataset is available on Kaggle : https://www.kaggle.com/datasets/blastchar/telco-customer-churn .

---

# Data Analysis

In [183]:
import numpy as np
import pandas as pd

In [184]:
df = pd.read_csv("data/telco_customer_churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [185]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

Well, most of the features matter imo to predict customer's churn. Only the ID of the Customer doesn't matter. So, we will remove it. You can read the details of each column on the kaggle website.

In [186]:
df = df.drop(columns="customerID")
df.head(1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No

---

## Analyzing the Columns

In [187]:
df.columns[0:10]

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup'],
      dtype='str')

### First 10 Columns

In [188]:
print(f'Unique Values in the "gender" col. : {(df["gender"].unique()).tolist()}')
print(f'Unique Values in the "SeniorCitizen" col. : {(df["SeniorCitizen"].unique()).tolist()}')
print(f'Unique Values in the "Partner" col. : {(df["Partner"].unique()).tolist()}')
print(f'Unique Values in the "Dependents" col. : {(df["Dependents"].unique()).tolist()}')
print("tenure is the number of months the customer has been with the company.")
print(f'Unique Values in the "PhoneService" col. : {(df["PhoneService"].unique()).tolist()}')
print(f'Unique Values in the "MultipleLines" col. : {(df["MultipleLines"].unique()).tolist()}')
print(f'Unique Values in the "InternetService" col. : {(df["InternetService"].unique()).tolist()}')
print(f'Unique Values in the "OnlineSecurity" col. : {(df["OnlineSecurity"].unique()).tolist()}')
print(f'Unique Values in the "OnlineBackup" col. : {(df["OnlineBackup"].unique()).tolist()}')

Unique Values in the "gender" col. : ['Female', 'Male']
Unique Values in the "SeniorCitizen" col. : [0, 1]
Unique Values in the "Partner" col. : ['Yes', 'No']
Unique Values in the "Dependents" col. : ['No', 'Yes']
tenure is the number of months the customer has been with the company.
Unique Values in the "PhoneService" col. : ['No', 'Yes']
Unique Values in the "MultipleLines" col. : ['No phone service', 'No', 'Yes']
Unique Values in the "InternetService" col. : ['DSL', 'Fiber optic', 'No']
Unique Values in the "OnlineSecurity" col. : ['No', 'Yes', 'No internet service']
Unique Values in the "OnlineBackup" col. : ['Yes', 'No', 'No internet service']

- I will convert the gender col. to numbers before training, as we have to visualize the data later so this format will be helpful.
- Col. # 3, 4 & 6 can be mapped easily with 1(Yes) and 0(No).
- About col. 7(MultipleLines), both "No Phone Service" and "No" can be mapped to 0(No).
- Same goes for "OnlineSecurity" and "OnlineBackup".
- We can use OHE on "InternetService" later.

### Last 10 Columns

In [189]:
df.columns[10:]

Index(['DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'Churn'],
      dtype='str')

In [190]:
print(f'Unique Values in the "DeviceProtection" col. : {(df["DeviceProtection"].unique()).tolist()}')
print(f'Unique Values in the "TechSupport" col. : {(df["TechSupport"].unique()).tolist()}')
print(f'Unique Values in the "StreamingTV" col. : {(df["StreamingTV"].unique()).tolist()}')
print(f'Unique Values in the "StreamingMovies" col. : {(df["StreamingMovies"].unique()).tolist()}')
print(f'Unique Values in the "Contract" col. : {(df["Contract"].unique()).tolist()}')
print(f'Unique Values in the "PaperlessBilling" col. : {(df["PaperlessBilling"].unique()).tolist()}')
print(f'Unique Values in the "PaymentMethod" col. : {(df["PaymentMethod"].unique()).tolist()}')
print("MonthlyCharges is amount charged to the customer monthly.")
print("TotalCharges is the total amount charged to the customer.")
print(f'Unique Values in the "Churn" col. : {(df["Churn"].unique()).tolist()}')

Unique Values in the "DeviceProtection" col. : ['No', 'Yes', 'No internet service']
Unique Values in the "TechSupport" col. : ['No', 'Yes', 'No internet service']
Unique Values in the "StreamingTV" col. : ['No', 'Yes', 'No internet service']
Unique Values in the "StreamingMovies" col. : ['No', 'Yes', 'No internet service']
Unique Values in the "Contract" col. : ['Month-to-month', 'One year', 'Two year']
Unique Values in the "PaperlessBilling" col. : ['Yes', 'No']
Unique Values in the "PaymentMethod" col. : ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
MonthlyCharges is amount charged to the customer monthly.
TotalCharges is the total amount charged to the customer.
Unique Values in the "Churn" col. : ['No', 'Yes']

- In Col. "DeviceProtection", both "No internet service" and "No" can be mapped to 0(No).
- Same goes for "TechSupport", "StreamingTV", and "StreamingMovies".
- On the "Contract" column, we can use Ordinal Encoding as there is a order. >> Month-to-month : 0, One Year : 1, Two Year : 2. 0<1<2. We'll work on this with Gender Col.
- We can use OHE on "PaymentMethod".
- And "PaperlessBilling" and "Churn" can be mapped easily.

---

## Data Preprocessing

In [191]:
df["Partner"] = df["Partner"].map({"Yes" : 1, "No" : 0})
df["Dependents"] = df["Dependents"].map({"Yes" : 1, "No" : 0})
df["PhoneService"] = df["PhoneService"].map({"Yes" : 1, "No" : 0})
df["MultipleLines"] = df["MultipleLines"].map({"Yes" : 1, "No" : 0, "No phone service" : 0})
df["OnlineSecurity"] = df["OnlineSecurity"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})
df["OnlineBackup"] = df["OnlineBackup"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})

In [192]:
print(f'Unique Values in the "Partner" col. : {(df["Partner"].unique()).tolist()}')
print(f'Unique Values in the "Dependents" col. : {(df["Dependents"].unique()).tolist()}')
print(f'Unique Values in the "PhoneService" col. : {(df["PhoneService"].unique()).tolist()}')
print(f'Unique Values in the "MultipleLines" col. : {(df["MultipleLines"].unique()).tolist()}')
print(f'Unique Values in the "OnlineSecurity" col. : {(df["OnlineSecurity"].unique()).tolist()}')
print(f'Unique Values in the "OnlineBackup" col. : {(df["OnlineBackup"].unique()).tolist()}')

Unique Values in the "Partner" col. : [1, 0]
Unique Values in the "Dependents" col. : [0, 1]
Unique Values in the "PhoneService" col. : [0, 1]
Unique Values in the "MultipleLines" col. : [0, 1]
Unique Values in the "OnlineSecurity" col. : [0, 1]
Unique Values in the "OnlineBackup" col. : [1, 0]

In [193]:
df["DeviceProtection"] = df["DeviceProtection"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})
df["TechSupport"] = df["TechSupport"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})
df["StreamingTV"] = df["StreamingTV"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})
df["StreamingMovies"] = df["StreamingMovies"].map({"Yes" : 1, "No" : 0, "No internet service" : 0})

df["PaperlessBilling"] = df["PaperlessBilling"].map({"Yes" : 1, "No" : 0})
df["Churn"] = df["Churn"].map({"Yes" : 1, "No" : 0})

In [194]:
print(f'Unique Values in the "DeviceProtection" col. : {(df["DeviceProtection"].unique()).tolist()}')
print(f'Unique Values in the "TechSupport" col. : {(df["TechSupport"].unique()).tolist()}')
print(f'Unique Values in the "StreamingTV" col. : {(df["StreamingTV"].unique()).tolist()}')
print(f'Unique Values in the "StreamingMovies" col. : {(df["StreamingMovies"].unique()).tolist()}')
print(f'Unique Values in the "PaperlessBilling" col. : {(df["PaperlessBilling"].unique()).tolist()}')
print(f'Unique Values in the "Churn" col. : {(df["Churn"].unique()).tolist()}')

Unique Values in the "DeviceProtection" col. : [0, 1]
Unique Values in the "TechSupport" col. : [0, 1]
Unique Values in the "StreamingTV" col. : [0, 1]
Unique Values in the "StreamingMovies" col. : [0, 1]
Unique Values in the "PaperlessBilling" col. : [1, 0]
Unique Values in the "Churn" col. : [0, 1]

- The columns I am leaving for now : "gender", "Contract".
- The columns I am leaving for OHE : "InternetService", "PaymentMethod".

---

## Dataframe

In [195]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   int64
 3   Dependents        7043 non-null   int64
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   int64
 6   MultipleLines     7043 non-null   int64
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   int64
 9   OnlineBackup      7043 non-null   int64
 10  DeviceProtection  7043 non-null   int64
 11  TechSupport       7043 non-null   int64
 12  StreamingTV       7043 non-null   int64
 13  StreamingMovies   7043 non-null   int64
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   int64
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   str
 19  Churn             7043 non-null   int64
dtypes: float64(1), int64(14), str(5)
memory usage: 1.1 MB

Agh...The TotalCharges Column in in str format. Let's try to find out why?

In [196]:
df["TotalCharges"].unique()

<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str

In [197]:
df["TotalCharges"].str.contains(" ").sum()

np.int64(11)

Okay...so...there are some blank spaces. Maybe between the amounts? let's see

In [198]:
df[df["TotalCharges"].str.contains(" ")]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,1,1,0,0,0,DSL,1,0,1,1,1,0,Two year,1,Bank transfer (automatic),52.55,,0
753,Male,0,0,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,20.25,,0
936,Female,0,1,1,0,1,0,DSL,1,1,1,0,1,1,Two year,0,Mailed check,80.85,,0
1082,Male,0,1,1,0,1,1,No,0,0,0,0,0,0,Two year,0,Mailed check,25.75,,0
1340,Female,0,1,1,0,0,0,DSL,1,1,1,1,1,0,Two year,0,Credit card (automatic),56.05,,0
3331,Male,0,1,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,19.85,,0
3826,Male,0,1,1,0,1,1,No,0,0,0,0,0,0,Two year,0,Mailed check,25.35,,0
4380,Female,0,1,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,20.00,,0
5218,Male,0,1,1,0,1,0,No,0,0,0,0,0,0,One year,1,Mailed check,19.70,,0
6670,Female,0,1,1,0,1,1,DSL,0,1,1,1,1,0,Two year,0,Mailed check,73.35,,0
6754,Male,0,0,1,0,1,1,DSL,1,1,0,1,0,0,Two year,1,Bank transfer (automatic),61.90,,0

If you look at it, all these total charges have the contract of 2 years. We can just multiply the monthly payment by 24 for these.

But first, we need to convert these spaces to NaN

In [199]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce") #errors="coerce" turns spaces into NaN

In [200]:
mask = df["TotalCharges"].isna()
df.loc[mask, "TotalCharges"] = df.loc[mask, "MonthlyCharges"] * 24

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   int64
 3   Dependents        7043 non-null   int64
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   int64
 6   MultipleLines     7043 non-null   int64
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   int64
 9   OnlineBackup      7043 non-null   int64
 10  DeviceProtection  7043 non-null   int64
 11  TechSupport       7043 non-null   int64
 12  StreamingTV       7043 non-null   int64
 13  StreamingMovies   7043 non-null   int64
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   int64
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   int64
dtypes: float64(2), int64(14), str(4)
memory usage: 1.1 MB

Now it looks better.

In [203]:
df.describe()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,0.483033,0.299588,32.371149,0.903166,0.421837,0.286668,0.344881,0.343888,0.290217,0.384353,0.387903,0.592219,64.761692,2281.286824,0.265370
std,0.368612,0.499748,0.458110,24.559481,0.295752,0.493888,0.452237,0.475363,0.475038,0.453895,0.486477,0.487307,0.491457,30.090047,2265.674979,0.441561
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,18.800000,0.000000
25%,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.500000,402.225000,0.000000
50%,0.000000,0.000000,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,70.350000,1396.250000,0.000000
75%,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,89.850000,3786.600000,1.000000
max,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.750000,8684.800000,1.000000

Well, everything else looks normal. Except min tenure of 0 Months...

In [207]:
df[df["tenure"] == 0].shape[0]

11

In [209]:
df[df["tenure"] == 0]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,1,1,0,0,0,DSL,1,0,1,1,1,0,Two year,1,Bank transfer (automatic),52.55,1261.2,0
753,Male,0,0,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,20.25,486.0,0
936,Female,0,1,1,0,1,0,DSL,1,1,1,0,1,1,Two year,0,Mailed check,80.85,1940.4,0
1082,Male,0,1,1,0,1,1,No,0,0,0,0,0,0,Two year,0,Mailed check,25.75,618.0,0
1340,Female,0,1,1,0,0,0,DSL,1,1,1,1,1,0,Two year,0,Credit card (automatic),56.05,1345.2,0
3331,Male,0,1,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,19.85,476.4,0
3826,Male,0,1,1,0,1,1,No,0,0,0,0,0,0,Two year,0,Mailed check,25.35,608.4,0
4380,Female,0,1,1,0,1,0,No,0,0,0,0,0,0,Two year,0,Mailed check,20.00,480.0,0
5218,Male,0,1,1,0,1,0,No,0,0,0,0,0,0,One year,1,Mailed check,19.70,472.8,0
6670,Female,0,1,1,0,1,1,DSL,0,1,1,1,1,0,Two year,0,Mailed check,73.35,1760.4,0
6754,Male,0,0,1,0,1,1,DSL,1,1,0,1,0,0,Two year,1,Bank transfer (automatic),61.90,1485.6,0

They have Churn 0. Could mean that they just Joined the firm. Let's leave them as they are.

---

## Saving the Dataframe

In [210]:
df.to_csv("data/cleaned_telco_customer_churn.csv", index=False)

There are still some columns that I need to work on after visualization : "InternetService", "PaymentMethod", "gender", "Contract".

---